on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY: ghcr.io/amsterdam

name: Release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: helm
          include-v-in-tag: false

      - uses: actions/checkout@v3

      - name: Install Helm
        if: ${{ steps.release.outputs.release_created }}
        uses: azure/setup-helm@v3

      - name: Install Node
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Login to GitHub Container Registry
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create package and push
        if: ${{ steps.release.outputs.release_created }}
        run: |
          make test
          VERSION=${{ steps.release.outputs.tag_name }} make push
          VERSION=${{ steps.release.outputs.major }} make push
          VERSION=${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} make push
