name: amsterdam-bereikbaarheid

services:
  app:
    build: &build-config
      context: .
      args:
        BUILD_ENV: prod
        NGINX_CONF: nginx.default.conf
    image: ${REGISTRY:-localhost:5001}/${REPOSITORY:-opdrachten/bereikbaarheid-frontend}:${VERSION:-latest}
    env_file: .env.prod
    environment: &environment
      TZ: Europe/Amsterdam
    ipc: host
    ports:
      - '5000:8080'

  test:
    build:
      <<: *build-config
      target: test
    env_file: .env.acc
    environment: *environment
    command: npm run test

  upgrade:
    build:
      <<: *build-config
      target: upgrade
    env_file: .env.dev
    environment: *environment
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: ncu -u --doctor --target minor
