services:
  web-dev:
    build:
      context: .
      args:
        BUILD_ENV: local
        NGINX_CONF: nginx.local.conf
      target: dev
    environment:
      TZ: Europe/amsterdam
    volumes:
      - '.:/srv/dev'
    ipc: host
    ports:
      - '3000:3000'
