trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

parameters:
  - name: versionOverride
    displayName: "[OPTIONAL] Build/deploy version override"
    type: string
    default: ' '

resources:
  repositories:
    - repository: templates
      type: git
      name: opdrachten/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: bereikbaarheid-frontend
    ${{ if ne(parameters.versionOverride, ' ') }}:
      version: ${{ parameters.versionOverride }}
    build:
      producedImages:
      - opdrachten/bereikbaarheid-frontend
    dev:
      pool: Opdrachten
      namespace: ns-ccc-opdr-ont-01-bereikbaarheid
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-ont-01-bereikbaarheid"
    test:
      pool: Opdrachten
      namespace: ns-ccc-opdr-tst-01-bereikbaarheid
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-tst-01-bereikbaarheid"
    acc:
      pool: Opdrachten
      namespace: ns-ccc-opdr-acc-01-bereikbaarheid
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-acc-01-bereikbaarheid"
    prod:
      pool: Opdrachten
      namespace: ns-ccc-opdr-prd-01-bereikbaarheid
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-prd-01-bereikbaarheid"
