image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  repository: opdrachten/bereikbaarheid-frontend
  tag: latest

labels:
  app: bereikbaarheid-frontend

network:
  allow-ingress:
    selector: app == 'bereikbaarheid-frontend'
    ingress:
      - action: Allow
    egress:
      - action: Allow

deployments:
  app:
    tempDirs:
      - /tmp
    containers:
      - name: main
        ports:
          - port: 8080
            name: http

jobs:
  certificate-init:
    secrets:
      - certificate
    annotations:
      helm.sh/hook: post-install,post-upgrade
    containers:
      - name: main
        command:
          - sleep
        args:
          - "1"

services:
  app:
    ports:
      - name: http
        port: 80
        targetPort: 8080
    selector:
      app: bereikbaarheid-frontend

ingress:
  external:
    className: nginx-external
    paths:
      - path: /
        service: app
        port: 80
    tls: certificate
  internal:
    className: nginx-internal
    paths:
      - path: /
        service: app
        port: 80
    tls: certificate
  internal-motiv:
    className: nginx-internal
    paths:
      - path: /
        service: app
        port: 80
    tls: certificate

secrets:
  certificate:
    type: keyvault
    tls: bereikbaarheid
