{{- $fullName := include "helm.fullname" $ }}
{{- $labels := include "helm.labels" $ -}}
{{- range $key, $value := .Values.configMaps | default list }}
{{- if ne .enabled false }}
{{- $context := dict "local" . "root" $ -}}
{{- $annotations := include "resource.annotations" $context }}
{{- $labels := include "resource.labels" $context }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $key }}-{{ $fullName }}"
  labels: {{ $labels | nindent 4 }}
  {{- with $annotations }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
data:
  {{- .data | toYaml | nindent 2 }}
---
{{- end }}
{{- end }}
