{{- $fullName := include "helm.fullname" $ -}}

{{- range $manifestName, $values := .Values.deployments }}
{{- if .autoscale }}
{{- $context := dict "local" . "root" $ -}}
{{- $annotations := include "resource.annotations" $context }}
{{- $labels := include "resource.labels" $context }}
{{- $selectorLabels := include "resource.selectorLabels" $context }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" $manifestName $fullName }}
  labels: {{ $labels | nindent 4 }}
  {{- with $annotations }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
spec:
  minReplicas: {{ .autoscale.min | default 1 }}
  maxReplicas: {{ .autoscale.max | default 3 | max 1 (add 1 .autoscale.min) }}
  metrics:
  {{- with .autoscale.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: {{ . }}
        type: Utilization
  {{- end }}
  {{- with .autoscale.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        averageUtilization: {{ . }}
        type: Utilization
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" $manifestName $fullName }}
{{- end }}
{{- end }}
