{{- $root := . -}}
{{- $fullName := include "helm.fullname" $ -}}

{{- range $manifestName, $values := $.Values.ingress }}
{{- if ne $values.enabled false }}

{{- $context := dict "local" . "root" $ -}}
{{- $annotations := include "resource.annotations" $context }}
{{- $labels := include "resource.labels" $context }}
{{- $selectorLabels := include "resource.selectorLabels" $context }}
{{- $host := required "Ingress must have a host" (.host | default $.Values.host)}}
---

{{/* {{- $svcPort := $values.service.port -}} */}}
{{- if and .className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .annotations "kubernetes.io/ingress.class" .className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $manifestName }}-{{ $fullName }}"
  labels:
    {{- $labels | nindent 4 }}
  {{- with $annotations }}
  annotations: 
    {{- . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .className | default "nginx-internal" }}
  {{- if $host }}
  {{- with .tls }}
  tls:
    - hosts:
        - {{ $host | quote }}
      {{- if kindIs "string" . }}
      secretName: {{ printf "%s-%s" . $fullName }}
      {{- else }}
      secretName: {{ .secretNameOverride | default (printf "%s-%s" .secretName $fullName) }}
      {{- end }}
  {{- end }}
  {{- end }}
  rules:
    - {{ if $host -}}
      host: {{ $host | quote }}
      {{ end -}}
      {{- with .paths }}
      http:
        paths:
          {{- range . }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ printf "%s-%s" (required "Ingress path needs a service" .service) $fullName }}
                port:
                  number: {{ required "Ingress path needs a port" .port }}
          {{- end }}
      {{- end }}

{{- end }}
{{- end }}

