{{- $root := . -}}
{{- $fullName := include "helm.fullname" $ -}}

{{- range $manifestName, $values := $.Values.persistentVolumeClaims }}
{{- if ne .enabled false }}

{{- $context := dict "local" . "root" $ -}}
{{- $annotations := include "resource.annotations" $context }}
{{- $labels := include "resource.labels" $context }}
{{- $selectorLabels := include "resource.selectorLabels" $context }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" $manifestName $fullName }}
  labels: {{ $labels | nindent 4 }}
  {{- with $annotations }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
spec:
  {{- with .storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .volumeName }}
  volumeName: {{ . }}
  {{- end }}
  {{- with .accessModes | default (list "ReadWriteOnce") }}
  accessModes: {{ toYaml . | nindent 4}}
  {{- end }}
  {{- with .resources }}
  resources: {{ toYaml . | nindent 4 }}
  {{- end }}

{{- end }}
{{- end }}

