{{- $fullName := include "helm.fullname" $ }}
{{- $labels := include "helm.labels" $ -}}
{{- range $key, $value := .Values.secrets | default list }}
{{- if ne .enabled false }}
{{- if eq (lower .type) "keyvault" }}
{{- $context := dict "local" . "root" $ -}}
{{- $annotations := include "resource.annotations" $context }}
{{- $labels := include "resource.labels" $context }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ printf "%s-%s" $key $fullName }}
  labels: {{ $labels | nindent 4 }}
  {{- with $annotations }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
spec:
  provider: {{ .provider | default "azure" | quote }}
  parameters:
    {{- with .workloadIdentity | default $.Values.workloadIdentity }}
    clientID: "{{ . }}"
    usePodIdentity: "false"
    useVMManagedIdentity: "false"        
    {{- else }}
    usePodIdentity: {{ .usePodIdentity | default false | quote }}
    {{- with .keyVaultIdentity | default $.Values.keyVaultIdentity }}
    userAssignedIdentityID: "{{ . }}"
    useVMManagedIdentity: "true"
    {{- end }}
    {{- end }}
    {{- with .keyVaultName | default $.Values.keyVaultName }}
    keyvaultName: "{{ . }}"
    {{- end }}
    {{- with .tenantId | default $.Values.tenantId }}
    tenantId: "{{ . }}"
    {{- end }}
    objects: |
      array:
      {{- with .tls }}
        - |
          objectName: {{ . | quote }}
          objectType: secret
      {{- end }}
      {{- range .secrets | default list }}
        - |
          objectName: {{ . | quote }}
          objectType: secret
      {{- end }}
  secretObjects:

    {{- with .tls }}
    - secretName: {{ printf "%s-%s" $key $fullName | quote }}
      type: kubernetes.io/tls
      data:
        - objectName: {{ . | quote }}
          key: tls.key
        - objectName: {{ . | quote }}
          key: tls.crt
    {{- end }}

    {{- with .secrets }}
    - secretName: {{ printf "%s-%s" $key $fullName | quote }}
      type: Opaque
      data:
      {{- range . }}
        - objectName: {{ . | quote }}
          key: {{ . | quote }}
      {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
