{{- $fullName := include "helm.fullname" $ }}
{{- $labels := include "helm.labels" $ -}}
{{- range $key, $value := .Values.secrets | default list }}
{{- if ne .enabled false }}
{{- if eq .type "opaque" }}
{{- $context := dict "local" . "root" $ -}}
{{- $annotations := include "resource.annotations" $context }}
{{- $labels := include "resource.labels" $context }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ $key }}-{{ $fullName }}"
  labels: {{ $labels | nindent 4 }}
  {{- with $annotations }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
stringData:
  {{- .secrets | toYaml | nindent 2 }}
---
{{- end }}
{{- end }}
{{- end }}
