{{- $fullName := include "helm.fullname" $ -}}
{{- range $manifestName, $values := .Values.serviceAccounts }}
{{- if ne .enabled false }}
{{- $context := dict "local" . "root" $ -}}
{{- $annotations := include "resource.annotations" $context }}
{{- $labels := include "resource.labels" $context }}
{{- $selectorLabels := include "resource.selectorLabels" $context }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-%s" $manifestName $fullName }}
  labels: 
    {{- $labels | nindent 4 }}
    {{- if ne .enableWorkloadIdentity false }}
    {{- with .workloadIdentity | default $.Values.workloadIdentity }}
    azure.workload.identity/use: "true"
    {{- end }}
    {{- end }}
  annotations: 
    {{- $annotations | nindent 4 }}
    {{- if ne .enableWorkloadIdentity false }}
    {{- with .workloadIdentity | default $.Values.workloadIdentity }}
    azure.workload.identity/client-id: {{ . }}
    {{- end }}
    {{- end }}

{{- end }}
{{- end }}
