host: localhost

image:
  imagePullPolicy: Always

jobs:
  certificate-init:
    enabled: false

ingress:
  app:
    tls: null

secrets:
  certificate:
    enabled: false

network:
  allow-ingress:
    enabled: false