host: localhost

image:
  imagePullPolicy: Always

jobs:
  certificate-init:
    enabled: false

ingress:
  external:
    enabled: false
  internal-motiv:
    enabled: false
  internal:
    className: nginx

secrets:
  certificate:
    enabled: false

network:
  allow-ingress:
    enabled: false
